apiVersion: v1
kind: Pod
metadata:
  name: anti-affinity
spec:
  affinity:
    nodeAffinity:
      # hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: NotIn
            values:
            - us-east-1b
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
